language: java

jdk:
 - oraclejdk8
 
notifications:
  email:
    - cs.pedrozo33@gmail.com
    
addons:
  apt:
    packages:
      - python-yaml

before_install:
  - git submodule update --init --recursive

before_script:
  - python etc/travis-sonatype.py

install:
 - pip install coveralls
 
script:
  - coverage run --source=src teste.java

after_success:
  - coveralls

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
