language: java

jdk:
 - oraclejdk8
 
notifications:
  email:
    - cs.pedrozo33@gmail.com
    
addons:
  apt:
    packages:
      - python-yaml

before_install:
 - git submodule update --init --recursive

install:
 - pip install coveralls
 
script:
 - run --source=travis/src/teste/java/br/com/qualister/triangulo

after_success:
 - coveralls

after_success:
 - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report
