language: java

jdk:
 - oraclejdk8
 
notifications:
  email:
    - cs.pedrozo33@gmail.com
    
install:
 - pip install coveralls
 
script:
  - coverage run --source=codigo_avulso_test_tutorial setup.py test

after_success:
  - coveralls
